### ISSUE TITLE
PHP Version

### ISSUE THREAD

**Issue by dungmediabridge** [yiiviet/yii2-payment#4]
![image](https://user-images.githubusercontent.com/41981016/46606655-326dff00-cb28-11e8-90a7-2a13320df75a.png)
Xampp mình cài php 7.2 không cài được.

**Comment by dungmediabridge** [comment]
để mình xem kỹ cái này xem 
![image](https://user-images.githubusercontent.com/41981016/46606785-b7591880-cb28-11e8-8f77-4c84b98f8a58.png)

**Comment by vuongxuongminh** [comment]
Bạn check lại php version của bạn thông qua command line `php -v` nếu là php 7.2 thì check tiếp `php version` trong `composer.json` ở project socbay1.vn
